// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/project-sections/ColoredBorder.tsx": () => import("../components/mockups/project-sections/ColoredBorder.tsx"),
  "./components/mockups/project-sections/PillBadge.tsx": () => import("../components/mockups/project-sections/PillBadge.tsx"),
  "./components/mockups/project-sections/TabToggle.tsx": () => import("../components/mockups/project-sections/TabToggle.tsx")
};
